version: "3.5"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-net
  broker:
    image: rabbitmq:3.6.6
    ports:
      - "5672:5672"
    env_file:
      - .env
    networks:
      - app-net
  app:
    build: .
    container_name: app
    command: bash -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - broker
    networks:
      - app-net
  worker:
    build: .
    container_name: worker
    command: celery -A src worker -l info
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app/

    depends_on:
      - db
      - broker
      - app
    restart: on-failure
    networks:
      - app-net
  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A src beat -l info
    volumes:
      - ./:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - db
      - broker
      - app
    networks:
      - app-net
networks:
  app-net:
    name: app-net
volumes:
  postgres_data: