# Generated by Django 4.2.6 on 2023-10-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=8)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("all_day", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_point_name",
                    models.CharField(help_text="Наименование ТП", max_length=255),
                ),
                ("address", models.CharField(help_text="Адрес ТП", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "открытая"), ("closed", "Закрытая")],
                        max_length=6,
                    ),
                ),
                ("rko", models.BooleanField()),
                ("office_type", models.CharField(max_length=255)),
                ("sale_point_format", models.CharField(max_length=255)),
                ("suo_avialability", models.BooleanField()),
                ("has_ramp", models.BooleanField()),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=8)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("metro_station", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days_of_week",
                    models.CharField(
                        choices=[
                            ("MON", "Пн"),
                            ("TUE", "Вт"),
                            ("WED", "Ср"),
                            ("THU", "Чт"),
                            ("FRI", "Пт"),
                            ("SAT", "Сб"),
                            ("SUN", "Вс"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("open_time", models.TimeField(null=True)),
                ("close_time", models.TimeField(null=True)),
                (
                    "service_mode",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Legal Entity"), (2, "Individual Person")]
                    ),
                ),
                ("is_serves", models.BooleanField(default=True)),
                ("is_weekend", models.BooleanField(default=True)),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="core.office",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AtmService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=255)),
                ("service_capability", models.CharField(max_length=255)),
                ("service_activity", models.CharField(max_length=255)),
                (
                    "atm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="core.atm",
                    ),
                ),
            ],
        ),
    ]
