# Generated by Django 4.2.6 on 2023-10-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "002_fill_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="atm",
            name="status",
            field=models.CharField(
                choices=[("open", "открытая"), ("closed", "Закрытая")], default="open"
            ),
            preserve_default=False,
        ),
    ]
